<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <script>  //p.373 예외 처리 구문 내부에서 사용하기(2)
    function test () {
      try {
        alert('A 위치입니다.')
        throw "예외 강제 발생"
      } catch (exception) {
        alert( 'B 위치입니다.')
        return
      } finally {
        alert('C 위치입니다.')
      }
    }

    //함수를 호출합니다.
    test()
  </script>
</head>
<body>
  
</body>
</html>